databases:
  - name: postgres
    ipAllowList: []
    databaseName: photofolio_render_production
    user: photofolio_render

services:
  - type: web
    name: photofolio_render
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false