databases:
  - name: Photofolio DB
    databaseName: dbphotofolio
    user: dbphotofolio_user

services:
  - type: web
    name: photofolio_render
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dbphotofolio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false